const list = [
  {
    id: 1,
    name: "Bogs",
    category: "boots",
    image: "./images/bogs.jpg",
    price: "2000",
    amount: 1,
  },
  {
    id: 2,
    name: "White Nike",
    category: "boots",
    image: "./images/nike.webp",
    price: "4000",
    amount: 1,
  },
  {
    id: 3,
    name: "Open Sandal",
    category: "sandals",
    image: "./images/sandal.jpg",
    price: "6000",
    amount: 1,
  },
  {
    id: 4,
    name: "Sketchers",
    category: "Sport Shoes",
    image: "./images/sketchers.jpg",
    price: "12000",
    amount: 1,
  },
  {
    id: 5,
    name: "Timberland",
    category: "boots",
    image: "./images/timberland.jpg",
    price: "8000",
    amount: 1,
  },
  {
    id: 6,
    name: "Crocs",
    category: "sandals",
    image: "./images/crocs.jpg",
    price: "2000",
    amount: 1,
  },
  {
    id: 7,
    name: "Nike Women",
    category: "ladies",
    image: "./images/women-nike.webp",
    price: "5500",
    amount: 1,
  },
  {
    id: 8,
    name: "Men Balance",
    category: "Sport Shoes",
    image: "./images/men-balance.webp",
    price: "2400",
    amount: 1,
  },
  {
    id: 9,
    name: "Basketball shoes",
    category: "Sport Shoes",
    image: "./images/basketball.webp",
    price: "600",
    amount: 1,
  },
];

export default list;